# Change these first
owner: arianpasquali # Your GitHub organization or username, where this repository lives
repo: upptime-monitor-example # The name of this repository

sites:
  - name: cl2-nlp (Epic)
    url: $EPIC_URL/v2/health

  - name: cl2-nlp (Epic) [endpoint:tenants]
    url: $EPIC_URL/v1/tenants?locale=en
    method: GET
    headers:
      - "Content-Type: application/json"
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-monitor-example
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
